import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Provider";
import Navbar from "./components/Navbar";
import { routes_without_header } from "./constants/routes_without_header";
import { headers } from "next/headers";
// import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();

  const headerList = headers();
  const pathname = headerList.get("x-current-path");

  console.log("pathname", pathname);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-7xl mx-auto">
          <div>
            {!routes_without_header.includes(pathname as string) && <Navbar />}
            <AuthProvider>{children}</AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
